### ISSUE TITLE
"Cost & Traffic Control" Issue

### ISSUE THREAD

**Issue by hunsenlong** [Dynatrace/openkit-js#78]
**Expected behavior**
Hello, I encountered some problems when using the latest version of openkit-js. When I set "Cost & Traffic Control" to 10 in dynatrace, a lot of data could not be captured. When I checked the source code, I found two pieces of code related to whether to send data. Among them, "trafficControlPercentage" is a random number when the session is initialized, and the other "trafficControlPercentage" is read from the dynatrace configuration, which is 10. The function "isCaptureDisabled" determines whether to send data. The logic is to compare the "trafficControlPercentage" generated by the session initialization with the configured "trafficControlPercentage". When the former is greater than or equal to the latter, no data is sent. I feel that this is unreasonable. Suppose I have 100 users, according to the setting of 10%. The data of 10 users should be sent to dynatrace. However, the probability of these 100 users hitting a number below 10 is very small according to the current logic.

**Screenshots**
1. ![d991a1d43e410425ee65c4e460bc85c](https://github.com/user-attachments/assets/c2afdaba-6b90-4edd-bc65-cbfc3576c73f)

2. ![c74fb2194d8e3a91393d77f194ea643](https://github.com/user-attachments/assets/91e83c4b-07e9-4f1f-9745-ea4787991c52)

**Comment by TheHighriser** [comment]
Hey, I am not fully sure about your question. You say "a lot of data could not be captured" but in parallel you stated, that you only allowed 10% of data, which essentially means we will not capture roughly 90%.

I say roughly because this is by design 10% when we look at infinite numbers/sessions. In a smaller group there could be offsets. But in your example when using 10%, in a range of 0-100 only 10 values would lead to the situation that capturing is allowed, which is in my opinion roughly ~10%.

**Comment by hunsenlong** [comment]
My doubt is that the hit rate is very small. For example, if there are 100 sessions and the 10% setting is used, the number of captured sessions is about 10. But the current result is not as expected.

**Comment by TheHighriser** [comment]
As said above the 10% are true when we are talking about an infinite number of sessions. If you only look at a small amount number like 100 sessions this might not be fully accurate and can be off.

Some mathematical background underlining this: https://en.wikipedia.org/wiki/Law_of_large_numbers.

**Comment by hunsenlong** [comment]
OK, thank you very much for your answer. I will inform the customer.
